<Project Sdk="Microsoft.NET.Sdk">

	<ItemGroup>
		<PackageReference Include="Quartz" />
		<PackageReference Include="Quartz.Extensions.Hosting" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\KhoiProjectManagement.Application\KhoiProjectManagement.Application.csproj" />
	</ItemGroup>

</Project>
