<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="BenchmarkDotNet" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\KhoiProjectManagement.Domain\KhoiProjectManagement.Domain.csproj" />
    <ProjectReference Include="..\KhoiProjectManagement.Application\KhoiProjectManagement.Application.csproj" />
    <ProjectReference Include="..\KhoiProjectManagement.Infrastructure\KhoiProjectManagement.Infrastructure.csproj" />
  </ItemGroup>

</Project>
